# Use the README file as a reference to customize settings.

Answer:
  fields:
    default: user_id, question_id, correct
    form: user_id, question_id, correct
  relationships: 
  application: Application
