# Use the README file as a reference to customize settings.

Question:
  fields:
    default: category_of_question_id, question, correct_answer, answer_1, answer_2, answer_3, rank, public, score, time
    form: category_of_question_id, question, correct_answer, answer_1, answer_2, answer_3, rank, public, score, time
  relationships: user_question, question_rating
  application: Application
