# Use the README file as a reference to customize settings.

Ranking:
  fields:
    default: category_of_question_id, rank, user_id, score
    form: category_of_question_id, rank, user_id, score
  relationships: 
  application: Application
