# Use the README file as a reference to customize settings.

UserFriend:
  fields:
    default: user_id, friend_id, friend_uid
    form: user_id, friend_id, friend_uid
  relationships: 
  application: Application
